### ISSUE TITLE
谢谢大佬

### ISSUE THREAD

**Issue by catshitz** [BruceKangCN/isMonthly#1]
thx

**Comment by BruceKangCN** [comment]
我也是这个windows版本，用起来并没有问题，你具体是在什么场景下闪退的？

**Comment by catshitz** [comment]
准确说是有较大概率打开后不显示GUI 任务管理器内有进程出现但很又就自动终止了 需多次尝试才有概率不会自动终止并显示出GUI 能够正常使用
您打包好的win版是precompiled 运行库这边也都有装 另外也在非系统盘也尝试了 症状一样
所以猜测不是缺少哪些前置运行条件或者权限不够（貌似便携版也不需要管理员权限）
所以不清楚到底是什么导致了这种闪退问题

**Comment by BruceKangCN** [comment]
刚才我直接用便携版试了下，确实有问题，因为我平时都是直接开发完用`Qt Creator`运行的，环境上可能有微妙的区别，我排查一下

**Comment by BruceKangCN** [comment]
排查了半天最后发现是启动时获取月额导致的崩溃，原因是我`QNetworkManager`的使用方式不对。现在修改完应该可以在启动时正确地使用异步方式获取月额了。

试下最新的2.5.3版（2.5.2只有些代码优化，没有功能修改，所以没放出来）

**Comment by catshitz** [comment]
感谢EZ大 已尝试最新pre_2.6.0 目前所有功能未见异常 且查询速度指数级提升(不知是不是法姆大佬接口处升级了)
唯一就是查询结果是乱序排列的 且同一批cid未改排序每次查询出的 id列表和结果页顺序 也是乱序不一致的(全部月额或全部非月额结果也每次分别会乱序不一致)
希望可以恢复之前按输入顺序得出查询结果的排序 或者查询页多一项点击 id/结果/码率 后分别按各项默认逻辑规则排序的功能(如cid点击后和windows一致按文本字符列表顺序倒序排列，结果点击后按 月额视频：是/月额视频：否 顺序倒序分类排列，码率点击后按 6000kbps/3000kbps 顺序倒序分类排列)

**Comment by BruceKangCN** [comment]
目前请求和返回结果都是没加过编号的，按返回顺序排序，所以异步请求会乱序，我最近也有增加排序功能的想法，有空会尝试做一下
