### ISSUE TITLE
3.3.0查询失败 3.0.0月额显示为非月额 2.6.1查询正常

### ISSUE THREAD

**Issue by catshitz** [BruceKangCN/isMonthly#2]
感谢大佬！

**Comment by BruceKangCN** [comment]
目前排查出是3.0.2升级到3.1.0时出现的问题，正在分析具体原因

**Comment by BruceKangCN** [comment]
错误原因是我把一个`QNetworkReply`进行了2次`readAll`操作...第一次可以正常取到内容，第二次取到的是空值，然后就导致了`JSON`解析错误，总之很淦
还有我的`3.0.0`貌似没问题，可以正常区分月额和非月额，如果你确定有问题的话就提供一下你所查询的`cid`

**Comment by catshitz** [comment]
抱歉大佬回晚了，3.3.1已测目前查询正常，感谢！
